# Generated by Django 4.1.3 on 2022-11-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_name',
            new_name='car_type',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_seats',
            field=models.IntegerField(),
        ),
    ]
