# Generated by Django 4.1.3 on 2022-11-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners_page', '0002_rename_car_name_car_car_type_alter_car_car_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_type',
            new_name='car_name',
        ),
    ]
