# Generated by Django 4.1.3 on 2022-11-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_page', '0003_rename_car_type_car_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default='numbers'),
        ),
    ]
