# Generated by Django 4.1.3 on 2022-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_page', '0004_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
